[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]

[project]
name = "veritaserum"
version = "0.0.1"

[options]
python_requires = ">=3.12.4"